# This is a basic workflow to help you get started with Actions

name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test and Build
    steps:
      - name: Install OpenGL deps
        run: |
          sudo apt update
          sudo apt install -y \
          libasound2-dev \
          libx11-dev \
          libxrandr-dev \
          libxi-dev \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          libxcursor-dev \
          libxinerama-dev \
          libwayland-dev \
          libxkbcommon-dev

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup ZIG
        uses: mlugg/setup-zig@v1
        with:
          version: master
          use-cache: true # Let's see how this behaves

      - name: Build
        run: zig build
