# This is a basic workflow to help you get started with Actions

name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test and Build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup ZIG
        uses: mlugg/setup-zig@v1
        with:
          version: master
          use-cache: true # Let's see how this behaves

      - run: zig version

      - run: zig env

      - name: Build
        run: zig build
